[package]
name = "client"
version = "0.1.0"
authors = ["masond <drmason13@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.5.1"
shared = { path = "../shared" }
wasm-bindgen = "0.2.58"

[dev-dependencies]
wasm-bindgen-test = "0.3.8"
